services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'laravel'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'feedbacker'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
